FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["S2O.GateWay.csproj", "./"]
RUN dotnet restore "S2O.GateWay.csproj"

COPY . .
RUN dotnet publish "S2O.GateWay.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "S2O.GateWay.dll"]